agent_info:
  name: PlanningDirector
  role: Planning Director
capabilities:
  - strategy_planning
  - roadmap_management
workspace:
  shared: ../../SharedWorkspace
tools:
  - planner
collaboration:
  workflows:
    - daily_operations
    - project_development
    - emergency_response